# Ejercicios Numpy II

## Ejercicio 1
1. Crea un array que vaya del 0 al 9 y que se llame `my_array`
2. Imprime por pantalla los elementos [9 7 5 3 1] en ese orden.

In [1]:
import numpy as np

In [2]:
my_array =  np.array(range(0,10))
my_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
print(my_array[10:0:-2])

[9 7 5 3 1]


## Ejercicio 2
Imprime por pantalla la secuencia [[8 7]] del array `my_array`

In [4]:
print(my_array[8:6:-1])

[8 7]


## Ejercicio 3
Imprime por pantalla la secuencia [[2 1 0]] de `my_array`

In [5]:
print(my_array[-8:-11:-1])

[2 1 0]


## Ejercicio 4
1. Crea una matriz de 4x5, con una secuencia del 1 al 20
2. Invierte totalmente la matriz. Tanto las filas, como las columnas

In [6]:
z = np.arange(1,21).reshape(4,5)
z

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

## Ejercicio 5

Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[1, 2],
       [6, 7]])
```

In [7]:
z[:2,:2]

array([[1, 2],
       [6, 7]])

## Ejercicio 6
Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[ 1,  3,  5],
       [11, 13, 15]])
```

In [8]:
z[::2, ::2]

array([[ 1,  3,  5],
       [11, 13, 15]])

## Ejercicio 7
Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[ 5,  4,  3,  2,  1],
       [10,  9,  8,  7,  6],
       [15, 14, 13, 12, 11]])
```

In [9]:
z[:3:1,::-1]

array([[ 5,  4,  3,  2,  1],
       [10,  9,  8,  7,  6],
       [15, 14, 13, 12, 11]])

## Ejercicio 8
Dado el siguiente array:

```Python
x = np.array(["Loro", "Perro", "Gato", "Loro", "Perro"])
```

Filtra el array para quedarte únicamente con los loros.

Resuélvelo de dos maneras diferentes

In [10]:
x = np.array(["Loro", "Perro", "Gato", "Loro", "Perro"])
x

array(['Loro', 'Perro', 'Gato', 'Loro', 'Perro'], dtype='<U5')

In [11]:
x = x[x == "Loro"]
x

array(['Loro', 'Loro'], dtype='<U5')

## Ejercicio 9
Crea una secuencia de 20 elementos y transformala en un array compuesto por 2 matrices de 5x2

In [12]:
secuencia = np.arange(20)
secuencia

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [63]:
array_compuesto = secuencia.reshape(2,5,2)
array_compuesto

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9]],

       [[10, 11],
        [12, 13],
        [14, 15],
        [16, 17],
        [18, 19]]])

## Ejercicio 10
Obtén el siguiente array, partiendo de la matriz del **ejercicio 4**
```Python
array([[20, 19, 18, 17, 16],
       [15, 14, 13, 12, 11],
       [10,  9,  8,  7,  6],
       [ 5,  4,  3,  2,  1]])
```

In [14]:
z

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [15]:
z[::-1,::-1]

array([[20, 19, 18, 17, 16],
       [15, 14, 13, 12, 11],
       [10,  9,  8,  7,  6],
       [ 5,  4,  3,  2,  1]])

## Ejercicio 11
Crea un array de 10 0s. ¿Cuánto ocupa en memoria?

Sustituye el 4to elemento por 1, e imprime el array por pantalla

In [16]:
array_0 = np.zeros(10)
array_0

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [17]:
print(f"Ocupa {array_0.nbytes} bytes.")

Ocupa 80 bytes.


In [62]:
array_0[3]=1
array_0

array([0., 0., 0., 1., 0., 0., 0., 0., 0., 0.])

## Ejercicio 12
Crea un vector que vaya del 10 al 49

Inviértelo

In [18]:
vector = np.arange(10,50)
print(vector)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [19]:
vector = vector[::-1]
print(vector)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


## Ejericio 13
Encuentra los indices de los valores que no sean 0 del siguiente vector [[1,2,0,0,4,0]]. El output sería [[0, 1, 4]]. [Encuentra el método apropiado en la documentación.](https://numpy.org/doc/)

In [20]:
v = np.array([1,2,0,0,4,0])
z = np.where(v != 0)
z

(array([0, 1, 4], dtype=int64),)

## Ejercicio 14
Crea una matriz de numeros aleatorios 10x10. Encuentra los valores mínimo y máximo.

In [21]:
import random

In [22]:
fff = np.random.randint(10,size=(10,10))
fff

array([[1, 3, 6, 9, 7, 7, 1, 4, 6, 2],
       [6, 6, 1, 5, 2, 3, 1, 0, 1, 4],
       [5, 8, 8, 9, 4, 3, 6, 4, 7, 3],
       [9, 6, 6, 0, 5, 8, 2, 0, 7, 8],
       [1, 4, 7, 4, 3, 9, 9, 7, 1, 9],
       [3, 0, 2, 4, 2, 0, 1, 1, 8, 1],
       [1, 7, 2, 4, 9, 0, 2, 9, 1, 4],
       [7, 5, 8, 5, 0, 9, 4, 9, 3, 6],
       [0, 7, 6, 6, 5, 4, 5, 5, 8, 2],
       [1, 0, 4, 7, 5, 9, 8, 0, 2, 2]])

In [23]:
fff.max()

9

In [24]:
fff.min()

0

## Ejercicio 15
Crea un vector aleatorio de tamaño 30 y calcula su media

In [25]:
vv = np.random.randint(10,size=(1,30))
vv

array([[7, 7, 5, 0, 7, 9, 9, 8, 2, 5, 8, 1, 9, 0, 4, 8, 1, 5, 8, 7, 3, 2,
        0, 2, 3, 3, 6, 1, 5, 2]])

In [26]:
np.average(vv)

4.566666666666666

## Ejercicio 16
Crea un array cuadrado de 2D, con las dimensiones que quieras, pero que todo el borde esté compuesto por 1s, y el interior por 0s

In [27]:
eee = np.zeros(25).reshape(5,5)
eee[-1] = 1
eee[0] = 1
eee[0:5,-1] = 1
eee[0:5,0] = 1
eee

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

## Ejercicio 17
Crea una matriz de 8x8, y rellénala con 0s y 1s. Tienes que replicar:
```Python
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]
```

In [28]:
qqq = np.full(shape=(8,8),fill_value=0)
qqq

array([[0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0]])

In [29]:
qqq = np.full(shape=(8,8),fill_value=0)
qqq[::-2,::-2] = 1
qqq[::2,::2] = 1
qqq

array([[1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1]])

## Ejercicio 18
Replica la matriz del apartado anterior, pero en este caso usando [la función `tile`](https://numpy.org/doc/stable/reference/generated/numpy.tile.html)

In [53]:
arr = np.stack((np.arange(2), np.arange(2)[::-1]))
arr_result = np.tile(np.tile(arr[::-1],(4,1))[::1],4)
arr_result

array([[1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1]])

## Ejercicio 19
Crea una matriz aleatoria de 5x5 y normaliza sus valores. Para normalizar tienes que restar sus valores por la media(`np.mean`) y dividir el resultado por la desviación estándar(`np.std`).

In [61]:
casi = np.random.randint(10,size=(5,5))
casi_norm = (casi - np.mean(casi)) / np.std(casi)
casi_norm

array([[-0.25175441,  1.00701763, -0.67134509,  1.42660831,  1.00701763],
       [ 0.58742695,  1.42660831, -1.51052644, -0.67134509, -1.51052644],
       [-1.09093577,  0.58742695, -1.09093577,  0.58742695, -1.09093577],
       [ 0.16783627, -0.67134509, -0.25175441,  1.84619899, -1.09093577],
       [ 0.58742695, -0.67134509,  0.58742695,  1.42660831, -0.67134509]])

## Ejercicio 20
1. Crea una secuencia de números que vayan del 0 al 10.
2. Crea un nuevo array, que parta del anterior, pero sustituya todos los elementos entre el 3 y el 8, por el valor -1
3. Crea un nuevo array que niegue todos los elementos entre el 3 y el 8

In [74]:
arx = np.arange(11)
arx

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [70]:
arx_new = arx.copy()
arx_new[4:8] = -1
arx_new

array([ 0,  1,  2,  3, -1, -1, -1, -1,  8,  9, 10])

In [71]:
arx_new_2 =np.hstack((arx[:4],arx[8:]))
arx_new_2

array([ 0,  1,  2,  3,  8,  9, 10])

## Ejercicio 21 
#### Bonus track. Mini hundir la flota para ir practicando.
##### Te ayudará a entender la lógica de la tarea Hundir la Flota.
1. Crea un tablero de 10x10 relleno del carácter espacio ( ).
2. Posiciona un par de barcos en [(0,1), (1,1)] y [(1,3), (1,4), (1,5), (1,6)]. Los barcos serán Os mayúsculas. Como ves, un barco de dos posiciones de eslora y otro de cuatro.
3. Recibe un disparo en uno de los barcos, sustituyendo la O por una X
4. Recibe un disparo en agua, sustituyendo uno de los espacios por un guión: -
5. Ignorando los disparos recibidos, ahora prueba a posicionar otro barco de 4 posiciones dentro del tablero, pero **de manera ALEATORIA.**

**TIP apartado 5**: El barco tendrá una posición inicial aleatoria dentro del tablero, y una orientación también aleatoria (N,S,E,O).

Por ejemplo, si tu posicion inicial fuese (5,0) y la orientación O, no podrias ponerlo porque se sale del tablero. Ahora bien, si fuese orientación este, si podrías, y ocuparía las posiciones [(5,0), (5,1), (5,2), (5,3)]. Por tanto tendrás que iterar con un bucle si es posible encajar el barco en el tablero, y el bucle terminará cuando lo consigas encajar. **Ojo con las posiciones donde ya hay barco!!!**

Usa `import random` para elegir las coordenadas aleatorias.

In [218]:
tablero = np.full((10,10), fill_value=" ")

tablero

array([[' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' '],
       [' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' '],
       [' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' '],
       [' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' '],
       [' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' '],
       [' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' '],
       [' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' '],
       [' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' '],
       [' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' '],
       [' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ']], dtype='<U1')

In [219]:
tablero[0:2,1] = "O"
tablero

array([[' ', 'O', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' '],
       [' ', 'O', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' '],
       [' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' '],
       [' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' '],
       [' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' '],
       [' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' '],
       [' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' '],
       [' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' '],
       [' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' '],
       [' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ']], dtype='<U1')

In [220]:
tablero[1,3:7] = "O"
tablero

array([[' ', 'O', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' '],
       [' ', 'O', ' ', 'O', 'O', 'O', 'O', ' ', ' ', ' '],
       [' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' '],
       [' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' '],
       [' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' '],
       [' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' '],
       [' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' '],
       [' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' '],
       [' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' '],
       [' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ']], dtype='<U1')

In [221]:
tablero[1][3] = "X"
tablero[3][2] = "-"
tablero

array([[' ', 'O', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' '],
       [' ', 'O', ' ', 'X', 'O', 'O', 'O', ' ', ' ', ' '],
       [' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' '],
       [' ', ' ', '-', ' ', ' ', ' ', ' ', ' ', ' ', ' '],
       [' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' '],
       [' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' '],
       [' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' '],
       [' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' '],
       [' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' '],
       [' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ']], dtype='<U1')

In [224]:
import random
#barco es +4
#posición inicial = random

while True:
    b = random.randint(0,9)
    c = random.randint(0,9)
    rand_pos = tablero[b,c]
    barco_ocupado = "O"

    #dirección puedo sacar un range(4) y dentro del que caiga decidir norte, sur, este o oeste, con if
    a = random.randint(1,4)

    #print("El número de dirección es:",a)

    if (a == 1 and b < 2) or (a == 2 and b > 6) or (a == 3 and c > 2) or (a == 4 and c < 6):
         pass

    else:

        if a == 1:
            """Dirección norte"""
            if barco_ocupado not in tablero[b:b-4:-1,c]:
                tablero[b:b-4:-1,c] = "O"
                print("Se ha creado un barco de 4 posiciones hacia el norte")
                break
            
            else:
                 continue

        elif a == 2:
            """Dirección sur"""
            if barco_ocupado not in tablero[b,c:c+4]:
                tablero[b:b+4,c] = "O"
                print("Se ha creado un barco de 4 posiciones hacia el sur")
                break

            else:
                 pass

        elif a == 3:
            """Dirección este"""
            if barco_ocupado not in tablero[b,c:c+4]:
                tablero[b,c:c+4] = "O"
                print("Se ha creado un barco de 4 posiciones hacia el este")
                break

            else:
                pass

        elif a == 4:
            """Dirección oeste"""
            if barco_ocupado not in tablero[b,c:c-4:-1]:
                tablero[b,c:c-4:-1] = "O"
                print("Se ha creado un barco de 4 posiciones hacia el oeste")
                break
            else:
                 pass

print(f"Las coordenadas de nuestro barco se situan en: x={c+1} y={b+1}.")
print(tablero)


Se ha creado un barco de 4 posiciones hacia el sur
Las coordenadas de nuestro barco se situan en: x=3 y=4.
[[' ' 'O' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' 'O' ' ' 'X' 'O' 'O' 'O' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' 'O' ' ']
 [' ' ' ' 'O' ' ' ' ' ' ' ' ' ' ' 'O' ' ']
 [' ' ' ' 'O' ' ' ' ' ' ' ' ' ' ' 'O' ' ']
 [' ' 'O' 'O' ' ' ' ' ' ' ' ' ' ' 'O' ' ']
 [' ' 'O' 'O' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' 'O' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' 'O' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']]


In [ ]:
tablero[1][1] = "O"